# Generated by Django 5.2.4 on 2025-07-13 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("poll_id", models.CharField(max_length=255, unique=True)),
                ("poll_title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=5000)),
                ("poll_start", models.BigIntegerField()),
                ("poll_end", models.BigIntegerField()),
                ("votes", models.IntegerField(default=0)),
                ("creator_wallet_key", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("votes", models.IntegerField(default=0)),
                (
                    "poll",
                    models.ForeignKey(
                        db_column="poll_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.poll",
                        to_field="poll_id",
                    ),
                ),
            ],
        ),
    ]
