# Generated by Django 5.2.4 on 2025-07-13 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="poll",
            field=models.ForeignKey(
                db_column="poll_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="api.poll",
                to_field="poll_id",
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="poll_end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="poll",
            name="poll_start",
            field=models.DateTimeField(),
        ),
    ]
