# Generated by Django 5.2.7 on 2025-12-16 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_candidate_poll_alter_poll_poll_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voter_pubkey', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='api.candidate')),
                ('poll', models.ForeignKey(db_column='poll_id', on_delete=django.db.models.deletion.CASCADE, related_name='votes_records', to='api.poll', to_field='poll_id')),
            ],
            options={
                'unique_together': {('poll', 'voter_pubkey')},
            },
        ),
    ]
